name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        continue-on-error: true
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this Laravel pull request and provide feedback on:
            - Code quality and Laravel best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            - Database migrations and models
            - Controller logic and validation
            - Blade template structure

            Be constructive and helpful in your feedback. Focus on Laravel-specific issues.

            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

      - name: Print Claude execution output
        if: always()
        run: |
          echo "Checking for Claude output..."
          if [ -f /home/runner/work/_temp/claude-execution-output.json ]; then
            echo "Claude output found:"
            cat /home/runner/work/_temp/claude-execution-output.json
          else
            echo "No Claude output file found"
          fi

      - name: Check Claude review status
        if: always()
        run: |
          if [ "${{ steps.claude-review.outcome }}" == "failure" ]; then
            echo "Claude review failed, but continuing..."
          else
            echo "Claude review completed successfully"
          fi

